### PR TITLE
added Auth path for Laravel 5

### PR DESCRIPTION
**Pull request by apropos**

### CODE REVIEW

**Comment by stevebauman** [comment]
Thanks!

**Comment by apropos** [comment]
until the change, I keep getting
NoUserLoggedInException in UserIdentificationTrait.php line 53:
Cannot retrieve user ID

**Comment by stevebauman** [comment]
Ah shoot merged on wrong branch. Can you submit this pull on the master branch if possible? If not that's ok I can have this fix up tomorrow morning with a new release tag.

**Comment by apropos** [comment]
okay, pull request for master branch sent.

**Pull request merged**
